# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
  - 1.7
  - nightly
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      script:
        julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          using Documenter;
          using Taxonomy;
          include("docs/make.jl");
          doctest(Taxonomy);'
      after_success: skip