name = "Taxonomy"
uuid = "10bb16a4-4bfc-432e-9419-4ca69c1a753c"
authors = ["banhbio <ban@kuicr.kyoto-u.ac.jp>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
