name: CI
permissions:
  contents: write # Allow GITHUB_TOKEN to push docs via HTTPS

on:
  push:
    branches: [ main ]
    tags: '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.10', '1.11', 'nightly' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        arch: [ x64 ]
        include:
          - os: ubuntu-latest
            version: '1.10'
            arch: x86

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ env.cache-name }}-
            ${{ runner.os }}-julia-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          file: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for Documenter to push to gh-pages with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      # Replace any SSH remote with HTTPS authenticated by GITHUB_TOKEN.
      - name: Force HTTPS for git pushes
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global --add safe.directory $(pwd)

      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If you still plan to use an SSH deploy key uncomment the next line, otherwise leave it blank.
          # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
